# Generated by Django 6.0.5 on 2026-05-07 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('allow_ai_training', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('qa_pair_count', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_bases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='core.project')),
            ],
            options={
                'db_table': 'knowledge_base',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QAPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Entry'), ('document', 'Document Upload'), ('web_scraped', 'Web Scraped'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('similar_questions', models.JSONField(blank=True, default=list)),
                ('embeddings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qa_pairs', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='knowledge_base.knowledgebase')),
                ('tags', models.ManyToManyField(blank=True, related_name='qa_pairs', to='core.tag')),
            ],
            options={
                'db_table': 'knowledge_base_qa_pair',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('incorrect', 'Incorrect Information'), ('outdated', 'Outdated'), ('other', 'Other')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('visitor_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qa_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='knowledge_base.qapair')),
            ],
            options={
                'db_table': 'knowledge_base_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteCrawl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('max_depth', models.PositiveIntegerField(default=2)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('excluded_patterns', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('pages_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_crawls', to='knowledge_base.knowledgebase')),
            ],
            options={
                'db_table': 'knowledge_base_website_crawl',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('embeddings_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website_crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='knowledge_base.websitecrawl')),
            ],
            options={
                'db_table': 'knowledge_base_crawled_page',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File'), ('html', 'HTML'), ('md', 'Markdown'), ('csv', 'CSV'), ('excel', 'Excel'), ('other', 'Other')], default='other', max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('embedding_model', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Entry'), ('document', 'Document Upload'), ('web_scraped', 'Web Scraped'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.knowledgebase')),
            ],
            options={
                'db_table': 'knowledge_base_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['knowledge_base', 'processing_status'], name='knowledge_b_knowled_be7dd7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['knowledge_base', 'status'], name='knowledge_b_knowled_e3eb43_idx'),
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['category'], name='knowledge_b_categor_1e6422_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crawledpage',
            unique_together={('website_crawl', 'url')},
        ),
    ]
