# Generated by Django 6.0.5 on 2026-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if staff is available to receive new chat assignments'),
        ),
    ]
