# Generated by Django 6.0.5 on 2026-05-07 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='visitors.visitorsession'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='visitors.visitor'),
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='visitors.visitorsession'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-last_message_at'], name='chat_conver_status_731933_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['visitor', '-last_message_at'], name='chat_conver_visitor_2a9406_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', '-created_at'], name='chat_messag_session_e35c30_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type', 'created_at'], name='chat_messag_sender__87817a_idx'),
        ),
    ]
