# Generated by Django 6.0.5 on 2026-05-07 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('phone_number', 'Phone Number'), ('amount', 'Amount'), ('plan_type', 'Plan Type'), ('date', 'Date'), ('location', 'Location'), ('account_number', 'Account Number'), ('transaction_id', 'Transaction ID'), ('product_name', 'Product Name'), ('duration', 'Duration'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('extraction_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.project')),
            ],
            options={
                'db_table': 'nlp_entity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('intent_code', models.CharField(choices=[('check_balance', 'Check Balance'), ('buy_data', 'Buy Data Bundle'), ('buy_airtime', 'Buy Airtime'), ('subscribe_plan', 'Subscribe to Plan'), ('complaint', 'Complaint'), ('greeting', 'Greeting'), ('escalate_to_human', 'Escalate to Human Agent'), ('account_issue', 'Account Issue'), ('network_issue', 'Network Issue'), ('billing_inquiry', 'Billing Inquiry'), ('other', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('training_samples_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_categories', to='core.project')),
            ],
            options={
                'db_table': 'nlp_intent_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NLPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('intent_classification', 'Intent Classification'), ('entity_extraction', 'Entity Extraction'), ('language_detection', 'Language Detection'), ('sentiment_analysis', 'Sentiment Analysis')], max_length=50)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('model_version', models.CharField(default='1.0.0', max_length=50)),
                ('base_model', models.CharField(default='AfroXLMR', max_length=100)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_models', to='core.project')),
            ],
            options={
                'db_table': 'nlp_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPPredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField()),
                ('detected_language', models.CharField(default='en', max_length=10)),
                ('predicted_intent', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('extracted_entities', models.JSONField(blank=True, default=list)),
                ('processing_time_ms', models.PositiveIntegerField()),
                ('model_used', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('corrected_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_prediction_logs', to='core.project')),
            ],
            options={
                'db_table': 'nlp_prediction_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['predicted_intent', '-created_at'], name='nlp_predict_predict_b0ae61_idx'), models.Index(fields=['confidence_score'], name='nlp_predict_confide_93517c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to='nlp_service.intentcategory')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nlp_training_sample',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intent_category', 'language'], name='nlp_trainin_intent__023b87_idx')],
            },
        ),
    ]
