# Generated by Django 6.0.5 on 2026-05-07 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_open_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname_zh', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('first_visit_time', models.DateTimeField(auto_now_add=True)),
                ('last_visit_time', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('visitor_send_count', models.PositiveIntegerField(default=0)),
                ('last_message_seq', models.PositiveIntegerField(default=0)),
                ('is_last_message_from_visitor', models.BooleanField(default=False)),
                ('is_last_message_from_ai', models.BooleanField(default=False)),
                ('last_offline_time', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('ai_disabled', models.BooleanField(default=None, null=True)),
                ('ai_fallback_retry_count', models.PositiveIntegerField(default=0)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('geo_region', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_isp', models.CharField(blank=True, max_length=100, null=True)),
                ('service_status', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('active', 'Active'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.platform')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.project')),
            ],
            options={
                'db_table': 'visitors_visitor',
                'ordering': ['-last_visit_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='visitors.visitor')),
            ],
            options={
                'db_table': 'visitors_session',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='VisitorTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_tags', to='core.tag')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_tags', to='visitors.visitor')),
            ],
            options={
                'db_table': 'visitors_visitor_tag',
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['platform_open_id', 'platform'], name='visitors_vi_platfor_16a398_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['service_status'], name='visitors_vi_service_7af259_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['is_online'], name='visitors_vi_is_onli_16a388_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitortag',
            unique_together={('visitor', 'tag')},
        ),
    ]
