# Generated by Django 6.0.5 on 2026-05-07 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsession',
            name='escalated_to',
            field=models.ForeignKey(blank=True, help_text='Staff member to whom the session was escalated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason for escalation to human agent', null=True),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='escalation_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when escalation occurred', null=True),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='Flag indicating if session requires human intervention'),
        ),
    ]
